services:
  - type: web
    name: ivr-ai-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: |
      playwright install
      gunicorn main:app
    plan: free
